


public class PromptGenerator
{
  //attributes
  public List<string> _prompts = new List<string>();

  //methods
  public string GetRandomPrompt()
  {
    _prompts = ["What am I grateful for today?",
    "What made me smile today?",
    "What challenges did I face today?",
    "How did I handle stress today?",
    "What did I learn about myself today?",
    "What are my top three priorities right now?",
    "What does my ideal day look like?",
    "Who inspires me and why?",
    "What fears are holding me back?",
    "What does success mean to me?",
    "If I had no fear, what would I do?",
    "What is one habit I want to build?",
    "How do I define happiness?",
    "What is one thing I can improve tomorrow?",
    "Who has had the biggest impact on my life?",
    "What makes me feel alive?",
    "What would I do if money wasn't an issue?",
    "What do I need to forgive myself for?",
    "How have I grown in the last year?",
    "What do I love about my current life?",
    "What would I tell my younger self?",
    "What do I need more of in my life?",
    "What do I need less of in my life?",
    "What am I most proud of?",
    "What does my inner voice say?",
    "What would a perfect weekend look like?",
    "What gives me peace of mind?",
    "How do I recharge when I feel drained?",
    "What does my ideal future look like?",
    "Who do I want to become?",
    "What am I most excited about right now?",
    "How do I define self-care?",
    "What does balance mean in my life?",
    "What are five things that bring me joy?",
    "What am I afraid to say out loud?",
    "What relationships do I value most?",
    "What does love mean to me?",
    "What boundaries do I need to set?",
    "What does freedom mean to me?",
    "When do I feel most confident?",
    "What’s a dream I’ve been putting off?",
    "What would I do differently if I knew no one would judge me?",
    "What are three words that describe me?",
    "What is something I want to let go of?",
    "How do I want to be remembered?",
    "What does creativity mean to me?",
    "What legacy do I want to leave?",
    "What makes me unique?",
    "What am I currently tolerating in my life?",
    "What message does my body have for me today?",
    "How do I show love to myself?",
    "When do I feel most alive?",
    "What’s something I want to celebrate today?",
    "What am I overthinking right now?",
    "What can I do to be kinder to myself?",
    "What’s one belief I want to change?",
    "What do I love doing, even if I’m not good at it?",
    "What’s one small win I had today?",
    "What’s something I want to try this year?",
    "How do I know when I’m on the right path?",
    "What kind of energy do I want to attract?",
    "What makes me feel at home?",
    "What does rest mean to me?",
    "What motivates me to keep going?",
    "What do I need to hear right now?",
    "What advice would I give to my future self?",
    "What’s one thing I’d do differently today?",
    "What am I resisting right now?",
    "What does vulnerability mean to me?",
    "What are my values?",
    "What makes me feel powerful?",
    "What would I do if I couldn’t fail?",
    "What does joy feel like in my body?",
    "How do I deal with disappointment?",
    "What is my relationship with change?",
    "What do I admire in others?",
    "What is one area I want to grow in?",
    "When do I feel most relaxed?",
    "What triggers my anxiety?",
    "What helps me feel grounded?",
    "How do I process emotions?",
    "How can I simplify my life?",
    "What do I want to manifest?",
    "How do I define strength?",
    "What is my relationship with time?",
    "What makes me feel worthy?",
    "What does trust mean to me?",
    "When do I feel most creative?",
    "How do I want to feel today?",
    "What would I do if I had unlimited time?",
    "What’s holding me back from healing?",
    "What old story do I need to rewrite?",
    "What makes me feel safe?",
    "How do I nurture my mental health?",
    "How can I celebrate my body today?",
    "What makes me laugh?",
    "What does being successful look like?",
    "How do I want to grow spiritually?",
    "What lessons have I learned this week?",
    "What’s one kind thing I can do for myself today?",
    "What advice would I give my best friend?",
    "What kind of support do I need?",
    "How do I practice gratitude?",
    "What helps me sleep well?",
    "What is my biggest dream?",
    "What makes me feel connected to others?",
    "When do I feel most disconnected?",
    "What’s something I’m avoiding?",
    "What new habit do I want to try?",
    "What does authenticity mean to me?",
    "What’s one thing I want to forgive today?",
    "How can I practice patience?",
    "What brings me peace?",
    "What excites me about the future?",
    "What’s one thing I can declutter today?",
    "What does success feel like emotionally?",
    "How do I deal with criticism?",
    "What helps me feel balanced?",
    "What do I want more fun in?",
    "What would my dream home look like?",
    "How do I handle failure?",
    "What scares me the most?",
    "What helps me feel hopeful?",
    "What are five things I love about myself?",
    "What makes me feel appreciated?",
    "What do I want to be known for?",
    "What do I want to say yes to?",
    "What do I need to say no to?"
  ];
    Random random = new Random();
    int alea = random.Next(100);
    return _prompts[alea];
  }

}